### ISSUE TITLE
Make public

### ISSUE THREAD

**Issue by DivadNojnarg** [blockr-org/blockr.cardinal#2]
@JohnCoene Can we make this repo public? Or is there a reason not to do it? I have to update the webR CRAN and can't build private repos.

**Comment by JohnCoene** [comment]
We can make it public I think, maybe check with @karmatarap

**Comment by DivadNojnarg** [comment]
Ok all good just checked. Will open it.

**Comment by JohnCoene** [comment]
We should rename it too, blockr.cardinal I guess
